#!/usr/bin/env python3
"""
Đọc artifact thực nghiệm và sinh ``docs/scientific-report/vnai-generated-metrics.tex``.

Chỉ ghi số có nguồn file; không ước lượng hay bịa.

Usage:
  python scripts/flow/generate_scientific_report_metrics.py \\
    --training-log models/phobert-ner-vn-flow-last/training_log.json \\
    --audit-json reports/audit_acq_admin_bridge_last.json
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = ROOT / "docs" / "scientific-report" / "vnai-generated-metrics.tex"


def _pct_from_unit_interval(x: float | None, digits: int = 2) -> str:
    """x in [0,1] -> percent string."""
    if x is None:
        return r"---"
    return f"{100.0 * float(x):.{digits}f}"


def _tex_escape(s: str) -> str:
    return (
        s.replace("\\", r"\textbackslash{}")
        .replace("{", r"\{")
        .replace("}", r"\}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("#", r"\#")
        .replace("&", r"\&")
    )


def _load_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def _tail_csv_row(path: Path) -> dict[str, str] | None:
    if not path.is_file():
        return None
    with path.open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    return rows[-1] if rows else None


def build_tex(
    training_log: Path | None,
    audit_json: Path | None,
    experiment_csv: Path | None,
) -> str:
    iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    ner_f1 = ner_prec = ner_rec = ner_tok = None
    n_train = n_eval = None
    train_src = "none"
    if training_log and training_log.is_file():
        data = _load_json(training_log)
        er = data.get("eval_results") or {}
        ner_f1 = float(er.get("eval_f1", er.get("f1", 0.0)))
        ner_prec = float(er.get("eval_precision", er.get("precision", 0.0)))
        ner_rec = float(er.get("eval_recall", er.get("recall", 0.0)))
        ta = data.get("token_accuracy")
        if ta is not None:
            ner_tok = float(ta)
        n_train = data.get("n_train")
        n_eval = data.get("n_eval")
        train_src = str(data.get("data_source") or "unknown")

    g1_pass = g2_pct = g3_pct = g3_fail = q_total = "---"
    if audit_json and audit_json.is_file():
        aud = _load_json(audit_json)
        ov = aud.get("overview") or {}
        gates = aud.get("gates") or {}
        g1 = gates.get("G1_mat_v1_duplicate_old_id_all_zero") or {}
        g2 = gates.get("G2_lineage_triple_inner_coverage_pct_ge_99_9") or {}
        g3 = gates.get("G3_denorm_P_D_W_same_admin_version_and_geo_hierarchy") or {}
        q_total = str(int(ov.get("total_rows") or 0))
        g1_pass = "1" if g1.get("pass") else "0"
        g2_pct = str(g2.get("pct", "---"))
        g3_pct = str(g3.get("pct_aligned_of_three_fk", "---"))
        g3_fail = str(g3.get("rows_failed", "---"))

    exp_note = "none"
    if experiment_csv and experiment_csv.is_file():
        row = _tail_csv_row(experiment_csv)
        if row:
            keys = list(row.keys())[:6]
            exp_note = "csv_last_row_keys=" + ",".join(keys)

    lines = [
        "% " + "=" * 72,
        "% AUTO-GENERATED by scripts/flow/generate_scientific_report_metrics.py",
        f"% UTC timestamp: {iso}",
        "% " + "=" * 72,
        "",
        r"\providecommand{\VNAIGENTrainLogPath}{"
        + _tex_escape(training_log.as_posix() if training_log else "none")
        + "}",
        r"\providecommand{\VNAIGENTrainSource}{" + _tex_escape(train_src) + "}",
        r"\providecommand{\VNAIGENNERFOnePct}{" + _pct_from_unit_interval(ner_f1) + "}",
        r"\providecommand{\VNAIGENNERPrecisionPct}{" + _pct_from_unit_interval(ner_prec) + "}",
        r"\providecommand{\VNAIGENNERRecallPct}{" + _pct_from_unit_interval(ner_rec) + "}",
        r"\providecommand{\VNAIGENNERTokenAccPct}{"
        + (_pct_from_unit_interval(ner_tok) if ner_tok is not None else r"---")
        + "}",
        r"\providecommand{\VNAIGENNERTrainN}{" + (str(n_train) if n_train is not None else r"---") + "}",
        r"\providecommand{\VNAIGENNEREvalN}{" + (str(n_eval) if n_eval is not None else r"---") + "}",
        "",
        r"\providecommand{\VNAIGENAuditQueueTotal}{" + _tex_escape(str(q_total)) + "}",
        r"\providecommand{\VNAIGENAuditGOnePass}{" + _tex_escape(str(g1_pass)) + "}",
        r"\providecommand{\VNAIGENAuditGTwoPct}{" + _tex_escape(str(g2_pct)) + "}",
        r"\providecommand{\VNAIGENAuditGThreePct}{" + _tex_escape(str(g3_pct)) + "}",
        r"\providecommand{\VNAIGENAuditGThreeFail}{" + _tex_escape(str(g3_fail)) + "}",
        "",
        r"\providecommand{\VNAIGENExperimentCsvNote}{" + _tex_escape(exp_note) + "}",
        "",
        r"% eval_f1 trong training_log là seqeval overall (Trainer key eval_f1),",
        r"% không nhất thiết trùng định nghĩa macro-F1 theo từng lớp thực thể trong luận.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--training-log", type=str, default=None)
    ap.add_argument("--audit-json", type=str, default=None)
    ap.add_argument("--experiment-csv", type=str, default=None)
    ap.add_argument("--out", type=str, default=str(DEFAULT_OUT))
    ns = ap.parse_args()

    tl = Path(ns.training_log).resolve() if ns.training_log else None
    aj = Path(ns.audit_json).resolve() if ns.audit_json else None
    ec = Path(ns.experiment_csv).resolve() if ns.experiment_csv else None
    out = Path(ns.out).resolve()

    tex = build_tex(tl, aj, ec)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(tex, encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
